### ISSUE TITLE
Restore compatibility with older simplesamlphp versions

### ISSUE THREAD

**Issue by joostd** [SURFnet/simplesamlphp-module-authtiqr#1]
Commit https://github.com/SURFnet/simplesamlphp-module-authtiqr/commit/ff3f48133df4e2f4baddbbd1b8436850d4cd0d02 fixes compatibility with recent simplesamlphp versions. See also:
https://simplesamlphp.org/docs/stable/simplesamlphp-sp-migration#section_4_2_2

However, some current distributions still use older SSP versions (e.g. debian still uses 1.11), and above commit breaks compatibility.

**Comment by lineke** [comment]
@joostd Do you want the old version to be the default and using a config option to switch to the new simplesamlphp, or do you want a config to switch to the old version?

**Comment by joostd** [comment]
Please let the config switch to the old version (so default to new simplesamlphp version).

**Comment by joostd** [comment]
Can you automate by dynamically determining the version used?
SimpleSAML_Configuration::getVersion()

See simplesamlphp/lib/SimpleSAML/Configuration.php

**Comment by lineke** [comment]
See updated pull

**Comment by joostd** [comment]
Tested on Ubuntu 14.04 using SimpleSAMLphp 1.11 from debian repo.
